apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    component: frontend
