apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  database-url: "{{ .Values.backend.env.DATABASE_URL }}"
  openai-api-key: "{{ .Values.backend.env.OPENAI_API_KEY }}"
  auth-secret: "{{ .Values.backend.env.BETTER_AUTH_SECRET }}"
